components:
    schemas:
        FacetConfiguration:
            properties:
                aggregationName:
                    description:
                        The name of the aggregation.
                    type: string
                attributes:
                    additionalProperties:
                        type: object
                    description:
                        Additional attributes for the facet.
                    type: object
                frequencyThreshold:
                    description:
                        Frequency threshold for showing the terms.
                    type: integer
                maxTerms:
                    description:
                        Maximum number of terms to be shown.
                    type: integer
                name:
                    description:
                        The name of the facet.
                    type: string
                values:
                    description:
                        The values / selections to be filtered by.
                    items:
                        type: object
                    type: array
            type: object
        SearchRequestBody:
            properties:
                attributes:
                    additionalProperties:
                        type: object
                    type: object
                facetConfigurations:
                    items:
                        $ref: "#/components/schemas/FacetConfiguration"
                    type: array
            type: object
        SearchResult:
            properties:
                dateModified:
                    description:
                        The last time the item was changed.
                    format: date-time
                    type: string
                description:
                    description:
                        The item's description.
                    type: string
                embedded:
                    type: object
                itemURL:
                    description:
                        The link to the embedded item.
                    format: uri
                    type: string
                score:
                    description:
                        The item's score.
                    format: float
                    type: number
                title:
                    description:
                        The item's title.
                    type: string
        Suggestion:
            properties:
                attributes:
                    type: object
                score:
                    format: float
                    type: number
                text:
                    type: string
            type: object
        SuggestionsContributorConfiguration:
            properties:
                attributes:
                    type: object
                contributorName:
                    type: string
                displayGroupName:
                    type: string
                size:
                    type: integer
            type: object
        SuggestionsContributorResults:
            properties:
                attributes:
                    type: object
                displayGroupName:
                    type: string
                suggestions:
                    items:
                        $ref: "#/components/schemas/Suggestion"
                    type: array
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.portal.search.rest.client', and version '1.0.9'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/search":
        post:
            description:
                "Search the company index for matching content. This endpoint is in development status and requires a feature flag: set feature.flag.LPS-179669 to true."
            operationId: postSearchPage
            parameters:
                - in: query
                  description:
                      Model class names to be searched for. Defaults to all.
                  name: entryClassNames
                  schema:
                      type: string
                - in: query
                  description:
                      The list of fields to be returned.
                  name: fields
                  schema:
                      type: string
                - in: query
                  name: nestedFields
                  schema:
                      type: string
                - in: query
                  name: restrictFields
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SearchRequestBody"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SearchRequestBody"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SearchResult"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SearchResult"
                                type: array
            tags: ["SearchResult"]
    /suggestions:
        post:
            operationId: postSuggestionsPage
            parameters:
                - in: query
                  name: currentURL
                  schema:
                      type: string
                - in: query
                  name: destinationFriendlyURL
                  schema:
                      type: string
                - in: query
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywordsParameterName
                  schema:
                      type: string
                - in: query
                  name: plid
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: scope
                  schema:
                      type: string
                - in: query
                  name: search
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            items:
                                $ref: "#/components/schemas/SuggestionsContributorConfiguration"
                            type: array
                    application/xml:
                        schema:
                            items:
                                $ref: "#/components/schemas/SuggestionsContributorConfiguration"
                            type: array
                required: false
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SuggestionsContributorResults"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SuggestionsContributorResults"
                                type: array
            tags: ["Suggestion"]